### ISSUE TITLE
Cannot build master via Docker (run_docker.sh)

### ISSUE THREAD

**Issue by tdrozdowski** [Hirevo/alexandrie#48]
For some reason the master I pulled on March 30th builds just fine.  The latest - no such luck:

>  --> src/db/mod.rs:2:5
  |
2 | use url::Url;
  |     ^^^ help: a similar path exists: `cookie::url`

**Comment by Hirevo** [comment]
Oops, good catch !  
The `url` dependency was indeed missing in the `Cargo.toml` used for Docker builds, causing this error to be raised.  
It should now be fixed by **#49**.
I expect that, in time, we'll have stronger automated tests to make sure that we never break Docker builds again.  
Sorry for the inconvenience.  
(do not hesitate to re-open the issue if the problem still shows up on your side)
