### ISSUE TITLE
Make CLI based fetch the default

### ISSUE THREAD

**Issue by alibila** [Hirevo/alexandrie#72]
The `libgit2` based git operations have some problems (with SSH).
There is a workaround for this problem: setting the `CARGO_NET_GIT_FETCH_WITH_CLI` environment variable to `true`.

If the CLI based git access has no known problems, then why not make CLI the default option?
This default could be overwritten by setting the `CARGO_NET_GIT_FETCH_WITH_CLI` environment variable to `false`, in case some users don't like the more sensible new default.

**Comment by Hirevo** [comment]
By default, Alexandrie already manages its crate index using the `git` command line utility instead of `libgit2`, as specified in the default `alexandrie.toml` file:
https://github.com/Hirevo/alexandrie/blob/1eb1b3c00f0a85c53dfe8bb6034198a02ba74f9e/alexandrie.toml#L20-L22

The issue with a crate index configured using SSH is that the issue we mentioned arises on the users' machine (the consumers of the libraries hosted by the instance) when they perform `cargo build` or `cargo search`.  
It is an issue happening outside of Alexandrie's reach.  

Fixing the default can only be done within Cargo itself; here is a [**direct link to the `libgit2` authentication handling in Cargo's source code**](https://github.com/rust-lang/cargo/blob/b9b30c8b8ebaddb19d68484f09f50190ca76036e/src/cargo/sources/git/utils.rs#L440).  
This is the piece of code that, reportedly, does not always find the needed credentials to pull/push through SSH.  
And by setting `CARGO_NET_GIT_FETCH_WITH_CLI`, we tell Cargo to not attempt to find the credentials and do things itself, but rather to let the system `git` utility to sort it out for us.

**Comment by alibila** [comment]
Your explanations clarified for me.

I have also found out from cargo's https://doc.rust-lang.org/cargo/reference/config.html , that instead of the environment variable CARGO_NET_GIT_FETCH_WITH_CLI, I can also write this
`
[net]
git-fetch-with-cli = true   # use the `git` executable for git operations
`
into top level cargo config file:

    Windows: %USERPROFILE%\.cargo\config.toml
    Unix: $HOME/.cargo/config.toml


Since this is an easy workaround, there is no need for changing any defaults, I changed my mind.
